css
menuCss
	^'
#qc-magritte-menu {
	position: absolute;
	bottom: 0;
	top: 0px;
	left: 0;
	padding: 45px 0 0 5px;
	margin: 0  15px 0 0;
	width: 130px;
	height: 100%;	
}
.qc-magritte-menu {
	display: block;
	padding: 0;
	margin: 0;
}
.qc-magritte-menu li {
	display: block;
	padding: 0;
	margin: 0;
	
}
.qc-magritte-menu li a {
	margin: 0;
	padding: 2px 4px;
	display:block;
	text-align: left;
	min-height: 20px;
	font-size: 14px; 
	line-height: 20px;
	color: #222222;
}
.qc-magritte-menu a:hover {
	color: #555555;
	text-decoration: none;
}
.qc-magritte-menu a:visited {
	color: #222222;
}
.qc-magritte-menu a:active {
	color: #222222;
}
.qc-magritte-menu a {
	font-weight: bold;
}
'