todo-list
todoListQuit
	<tutorial>
	^QCTutorial new
		priority: 110;
		title: 'Open items';
		chapter: 'Todo List';
		description: 'When all went successfull there are now two menu items: one showing the todo list, and one showing all items, including the items that are completed. When you press the button completed, it should be removed from the todolist; and re-opening an item should add it to the todolist.';
		addExplanation: 'Save and quit the image and proceed with the next chapter.';
		yourself