installation
tutorialTestDownload
	<tutorial>
	^QCTutorial new
		priority: 50;
		title: 'Test download';
		chapter: 'Installation';
		description: 'Open a web browser on http://localhost:8080/ to confirm that things are up and running correctly. You can poke around a bit here, but don’t get too distracted at this point. We’ll be exploring QCMagritte in more detail in Chapter 2: Hello world';
		" add a picture of the webpage with a red circle around the link."
		yourself
		