installation
tutorialSaveAsDialog
	<tutorial>
	^QCTutorial new
		priority: 80;
		title: 'Save as dialog...';
		chapter: 'Installation';
		description: 'This will open a dialog asking for a name for the new image. Name the new image ‘backup.image’ and click OK or press <Enter>. This gives us a ‘clean’ or ‘virgin’ image that can be restored without downloading everything again from the web or copying from a CD/DVD.';
		" add a picture of the pharo image with the save as dialog "
		yourself
		