installation
tutorialSaveImageAs
	<tutorial>
	^QCTutorial new
		priority: 70;
		title: 'Save image as...';
		chapter: 'Installation';
		description: 'Smalltalkers refer to the above action as “saving the image,” and this is a handy way to preserve your changes and the environment. Think of it as a suspend action (or hibernate) for your computer. When you come back and restart your computer the same windows will be open in the same location with the same contents. If you are about to try something that might cause a problem, you could save the image before taking the risky action. Then, if things go bad you can quit without saving (see step #10 below) and simply reopen the saved image to get back to the prior state. Alternatively, you can change the name of the saved image by selecting the ‘save as…’ menu item.';
		" add a picture of the pharo image with world menu on save as... "
		yourself
		