installation
tutorialLaunch
	<tutorial>
	^QCTutorial new
		priority: 30;
		title: 'Launch';
		chapter: 'Installation';
		description: 'Find the executable appropriate for your operating system: Mac, Windows, or Linux. On the Macintosh, the folder will appear as a starfish icon representing an application package. On Windows, the folder can be opened to find various items, including a shortcut named ‘QCMagritte’. On Linux, the folder can be opened to find various items, including ‘QCMagritte.sh’. Double click on the appropriate icon to launch the executable.';
		" add a pictures of the several folder icons with the icons. "
		yourself
		