as yet unclassified
applicationFeatures
	<tutorial>
	^QCTutorial new
		priority: 10;
		title: 'The features of the default application';
		chapter: 'A Default Application';
		description: 'QCMagritte consist of a large number of parts that can be combined in different ways. QCApplication and QCApplicationModel show an easy way to combine them. Subclass both to have an easy start.';
		addExplanation: 'A QCMagritte application uses a tree of components/pages.  ';
		yourself.
