hello-world
chapterHelloWorld
	<chapter>
	^QCChapter new
		priority: 30;
		title: 'Hello world';
		description: 'When learning a new programming language it is traditional to start with a "Hello World!" application (see http://en.wikipedia.org/wiki/Hello_world_program). We will follow that practice and use this oppertunity to introduce you to the programming enviornment and the Smalltalk programming language.';
		yourself
		