installation
chapterInstallation
	<chapter>
	^(QCChapter on: self)
		priority: 10;
		title: 'Installation';
		description: 'For our first QCMagritte project we will use the “QCMagritte One-Click Experience” in Pharo. If this tutorial came with a DVD, copy ‘QCMagritte.app’ to your desktop and skip to step "Launch". Otherwise, follow steps "Download" and "Unpack" to download Seaside from the web.';
		yourself
		