todo-list
chapterSmalltalk
	<chapter>
	^(QCChapter on: self)
		priority: 50;
		title: 'Smalltalk';
		description: 'I probably should discus some of the properties of smalltalk here, as well as of Seaside. Important tools are the debugger, refactoring possibilities, preserving state, adding libraries and such. I probably went a bit fast at some points in chapter 5 for users who do not know smalltalk.';
		yourself
		