user-management
chapterUserManagement
	<chapter>
	^(QCChapter on: self)
		priority: 70;
		title: 'User management';
		description: 'Now that we have a todolist with projects, the next logical step would be adding users and allowing users to manage their own things. So in this chapter we will add users, a login, a team to the project, and basic security.
		This chapter is work in progress';
		yourself
		