todo-list
chapterTodoList
	<chapter>
	^(QCChapter on: self)
		priority: 40;
		title: 'Todo List';
		description: 'At this point we are going to start building a simple application to demonstrate some basic QCMagritte functionality and introduce you to more Smalltalk and Pharo as we go along. The application will allow you to maintain a simple todo list, that allows new items to be added and existing items to be "completed". Instead of starting with a user interface, we will start with a domain model that holds a todo item.';
		yourself
		