todo-list
chapterSmalltalk
	<chapter>
	^(QCChapter on: self)
		priority: 50;
		title: 'Smalltalk';
		description: 'I probably should discus some of the properties of smalltalk here, as well as of Seaside. Important tools are the debugger, refactoring possibilities, preserving state, adding libraries and such. I will skip this for now. The tutorial on Seaside done by James Foster (http://seaside.gemtalksystems.com/tutorial.html) is a very good tutorial that explains such concepts. Having followed the first 4 chapters of this tutorial, should make it possible to start with chapter 5 of that tutorial. You can continue working in the QCMagritte image without any problems.';
		yourself
		