explore
exploreDetails
	<tutorial>
	^QCTutorial new
		priority: 30;
		title: 'Details';
		chapter: 'Exploring QCMagritte';
		description: 'This tutorial should learn you the most important features of QCMagritte. As you can see, you can go to details. Press details to see the details of this item.';
		addExplanation: 'Some things will be shown in the details that do not show in the overview. By default the explanation is only visible in the details. Use the close button to go back to the overview, as the next item concerns the overview.';
		yourself
		