explore
exploreExamples
	<tutorial>
	^QCTutorial new
		priority: 20;
		title: 'Examples';
		chapter: 'Exploring QCMagritte';
		description: 'QCMagritte is shipped with a few examples. There could be more examples, but it is a beginning. Go to localhost:8080/browse and click on QCMagritte. Here you can see all demo''s that are installed together with QCMagritte. These demo''s gives an impression of some of the things we will come across.';
		yourself
		