explore
exploreSeaside
	<tutorial>
	^QCTutorial new
		priority: 10;
		title: 'Seaside and Magritte';
		chapter: 'Exploring QCMagritte';
		description: 'QCMagritte is build on top of 2 frameworks: Seaside and Magritte. On Seaside there are several tutorials, and they can be found on the official Seaside website: www.seaside.st. If you are new to Smalltalk and Seaside, it might be a good idea to follow a tutorial on Seaside first. We will not explain the concepts of Seaside in the tutorial, as this work is already done very well by James Foster.
The second framework that is used is Magritte. As this framework has less documentation, we will cover the concepts of Magritte in this tutorial as well.';
		yourself
		