hello-world
helloWorldBrowse
	<tutorial>
	^QCTutorial new
		priority: 110;
		title: 'Browse';
		chapter: 'Hello world';
		description: 'If the above steps were successful, you should be able to open a web browser on http://localhost:8080/ and click on the ‘Browse’ link.
The ‘Browse Installed Applications’ page gives you a list of the top-level links being served from by this web server, including our new ‘HelloWorld’ application.';
		yourself
		