hello-world
helloWorldWorkspace
	<tutorial>
	^QCTutorial new
		priority: 20;
		title: 'Workspace';
		chapter: 'Hello world';
		description: 'The workspace (The text area in the top right labeled "QCMagritte") provides a text area in which you can evaluate expressions and (optionally) display or inspect the results. Since this might be your first exposure to Smalltalk code, we''ll give a brief introduction to evaluating Smalltalkcode in a workspace. (If you already know Smalltalk or are just impatient, you can skim or skip this part!)
Click in the Workspace window at the bottom, at the end of the line with the phase ... Press <enter> a couple of times to get some space, and then type the following:
5 factorial. The workspace should look as follows:';
		" add a picture of the image "
		yourself
		