hello-world
helloWorldBrowse
	<tutorial>
	^QCTutorial new
		priority: 110;
		title: 'Browse';
		chapter: 'Hello world';
		description: 'If the above steps were successful, you should be able to open a web browser on http://localhost:8080/browse. The browse Installed Applications page gives you a list of the top-level links being served from by this web server, including our new HelloWorld application.';
		addExplanation: 'Open your HelloWorld application and see that is shown in a bootstrap template. On the top left you can now go back to your "starting" point of the application. As we have nothing else implemented, it indicates we need a model to proceed.';
		yourself
		