todo-list
todoListFirstVersion
	<tutorial>
	^QCTutorial new
		priority: 70;
		title: 'First version';
		chapter: 'Todo List';
		description: 'Now we can check our website if it is working. Go to "Hello World" in the browser and press reload. It should add "Todo" in the menu, and since this is the first item, automatically select it.';
		addExplanation: 'You should see the following screen:';
		addExplanation: 'Now we are going to test this application by adding some todo items. Just fill them out how you like.';
		addExplanation: 'Note that the user can double-click an item to edit this item inline in the report (same as the edit-button). Also adding will simply "add" the items, and removing will need a confirmation before the remove is actually committed. So the user can always undo his action quite easily.';
		addExplanation: 'Also there is a button where we can go to the details. This will open a new page where you can edit the item as well.';
		yourself