installation
tutorialSaveImage
	<tutorial>
	^QCTutorial new
		priority: 60;
		title: 'Save image';
		chapter: 'Installation';
		description: 'As we go along, we will be creating and editing code and other objects in the Pharo object space. To make the change persistent, you need to make a snapshot of the current object space—creating a new “image” (following a camera metaphor). To do this, left-click on the background (or desktop) to bring up the World menu and select ‘save’ from the menu. This will write out your changes to the default ‘seaside.image’ file that will be read when you next launch the QCMagritte One-Click Experience.';
		" add a picture of the pharo image with world menu on save "
		yourself
		