tutorials
tutorialOverview
	<tutorial>
	^QCTutorial new
		priority: 30;
		title: 'Overview';
		description: 'Since the overview is for most application the first entry point, we will start by explaining the options of the overview. The overview can be changed by the user. Your first assignment is to add the explanation to the overview. If you need a hint, go to the details to see the explanation';
		explanation: 'For adding an extra column you should go to the report options ... and click on choose columns. Here you can drag the columns to be (in)visible.';
		yourself
		