tutorials
tutorialDetails
	<tutorial>
	^QCTutorial new
		priority: 20;
		title: 'Details';
		description: 'This tutorial should learn you the most important features of QCMagritte. As you can see, you can go to details. Press details to see the details of this item.';
		explanation: 'Some things will be shown in the details that do not show in the overview. By default the explanation is only visible in the details. Go back to the overview for the next tutorial item.';
		yourself
		