installation
tutorialBackupImage
	<tutorial>
	^QCTutorial new
		priority: 90;
		title: 'Back up';
		chapter: 'Installation';
		description: 'To see the new file, open the application folders ‘Contents’ then ‘Resources’ (on the Mac you will need to right-click on the Application icon and select ‘Show Package Contents’). If you ever want to start over, simply delete ‘Seaside.changes’ and ‘Seaside.image,’ copy ‘backup.changes’ and ‘backup.image,’ and rename the copies to ‘Seaside.changes’ and ‘Seaside.image’ (note that capitalization might be important, depending on your platform).';
		" add a picture of Resources folder "
		yourself
		