installation
tutorialQuit
	<tutorial>
	^QCTutorial new
		priority: 100;
		title: 'Quit';
		chapter: 'Installation';
		description: 'Now we are ready to quit the application. Left click on the background to bring up the (now familiar) World menu and select the last item, ‘quit.’ In the ‘Save changes before quitting?’ dialog, select ‘No’ to quit without saving (since we already saved two images of the current object space).';
		" add a picture of world menu and the quit dialog "
		yourself
		