user-management
userManagementUsers
	<tutorial>
	^QCTutorial new
		priority: 10;
		title: 'Users';
		chapter: 'User management';
		description: 'We want to add users to the application. In the QC-Magritte framework we already have users.';
		addExplanation: 'Open your HelloWorld application and see that is shown in a bootstrap template. On the top left you can now go back to your "starting" point of the application. As we have nothing else implemented, it indicates we need a model to proceed.';
		yourself
		