user-management
userManagementTeam
	<tutorial>
	^QCTutorial new
		priority: 40;
		title: 'Team';
		chapter: 'User management';
		description: 'You can see that QC Magritte has the "normal" user management system using CRUD rights available. Now we are going to make things more complex, by creating a team to a project. This team should of course be able to see everything on his/her project, but not on other projects.';
		addExplanation: 'First we are going to add a description for the team members in the project. Since the team members are actually the normal users, we are going to use the following description:';
		addCode: '';
		yourself
