explore
exploreDetails
	<tutorial>
	^QCTutorial new
		priority: 30;
		title: 'Details';
		chapter: 'Exploring QCMagritte';
		description: 'This tutorial should teach you the most important features of QCMagritte. As you can see, you can go to details. Press details to see the details of this item.';
		addExplanation: 'Some things will be shown in the details that do not show in the overview. By default the explanation is only visible in the details. If you have used the "start" button to start this chapter, you will have skipped the overview of the chapter "Exploring QCMagritte". You can open the overview of the chapter by clicking on the list icon in the homepage. Open the overview of the chapter, as the next item concerns the overview.';
		yourself
		