explore
exploreOverview
	<tutorial>
	^QCTutorial new
		priority: 40;
		title: 'Overview';
		chapter: 'Exploring QCMagritte';
		description: 'Since the overview is for most applications the first entry point, this is an important screen for the user. This overview can be changed by the user. Why don''t you try to add the explanation to the overview, you just saw in the details. If you need a hint, go to the details to see the explanation';
		addExplanation: 'For adding an extra column you should go to the report options ... and click on choose columns. Here you can drag the columns to be (in)visible.';
		yourself
		