explore
exploreChapter
	<tutorial>
	^QCTutorial new
		priority: 80;
		title: 'Chapter';
		chapter: 'Exploring QCMagritte';
		description: 'When you look at the magritte-description of the class "QCChapter" it has a number of tutorials. When you look at the website, a chapter also has a title and a description.';
		addExplanation: 'A magritte description is build up, using the hierarchy of the object. As a chapter is a tutorial item, the magritte-descriptions of the tuturial items are also processed. Here you can find the descriptions of the title, description and priority.';
		addExplanation: 'The description of the priority is a bit of an odd one, as this one is not visible. You should be able to make it visible, using the report options in the overview of the chapters. Here you can also see that there are more description in the hierarchy of a QCChapter.';
		yourself
		