css
contentCss
	^'
#demo-content { 
	margin-left: 140px;
}
.ui-menu {
	display: block;
}
.ui-menu li {
	display: block;
	width: 250px;
	border: 1px solid black;
	background: white;
}
.filter-input {
	width: 95%;
	margin-right: 6px;
}
.commands {
	display: block;
	width: 100px;
}
.columns {
	float: left;
	min-height: 150px;
	min-width: 49%;
	display: block;
}
.columns h2 { 
	margin: 0;
	font-size: 20px;
	line-height: 20px;
}
.column-data { 
	min-height: 100px;
}
.overview-report form { 
	margin: 0; }
'