tutorial
smalltalk
	<tutorial>
	^QCTutorial new
		priority: 10;
		title: 'Smalltalk background';
		chapter: 'Technical Details';
		description: 'I probably should start to some of the properties of smalltalk here, as well as of Seaside. Important tools are the debugger, refactoring possibilities, preserving state, adding libraries and such. There are already quite a few good tutorials on these topics. So I will skip this for new.';
		addExplanation: 'I personally liked the tutorial of Seaside done by James Foster (http://seaside.gemtalksystems.com/tutorial.html) best. This is a very good tutorial that explains such concepts.';
		yourself